#!/usr/bin/env bash

# NxScraper Engine - Interactive Setup Script
# Configures all API keys and environment variables in one go

set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   NxScraper Engine - Setup Wizard         ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}\n"

ENV_FILE=".env"
COMPOSE_FILE="docker-compose.yml"

# Check if .env exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  .env file already exists!${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}Setup cancelled.${NC}"
        exit 1
    fi
    cp "$ENV_FILE" "${ENV_FILE}.backup"
    echo -e "${GREEN}✓ Backup created: ${ENV_FILE}.backup${NC}\n"
fi

# Function to prompt for input with default
prompt_input() {
    local var_name=$1
    local description=$2
    local default=$3
    local secret=${4:-false}
    
    echo -e "${BLUE}${description}${NC}"
    if [ -n "$default" ]; then
        echo -e "${YELLOW}  (Press Enter for default: ${default})${NC}"
    fi
    
    if [ "$secret" = true ]; then
        read -s -p "  > " value
        echo
    else
        read -p "  > " value
    fi
    
    if [ -z "$value" ] && [ -n "$default" ]; then
        value=$default
    fi
    
    echo "$value"
}

# Start configuration
echo -e "${GREEN}📝 Let's configure your NxScraper Engine!\n${NC}"

# Basic Configuration
echo -e "${BLUE}=== Basic Configuration ===${NC}\n"

NODE_ENV=$(prompt_input "NODE_ENV" "Environment (development/production)" "production")
API_PORT=$(prompt_input "API_PORT" "API Port" "3000")
LOG_LEVEL=$(prompt_input "LOG_LEVEL" "Log Level (debug/info/warn/error)" "info")
WORKER_CONCURRENCY=$(prompt_input "WORKER_CONCURRENCY" "Worker Concurrency" "5")

echo ""

# Database
echo -e "${BLUE}=== Database Configuration ===${NC}\n"
DRAGONFLY_URL=$(prompt_input "DRAGONFLY_URL" "DragonflyDB URL" "redis://dragonfly:6379")

echo ""

# Security
echo -e "${BLUE}=== Security ===${NC}\n"
echo -e "${YELLOW}Generating session encryption key...${NC}"
SESSION_KEY=$(openssl rand -hex 32)
echo -e "${GREEN}✓ Generated${NC}\n"

# LLM Providers
echo -e "${BLUE}=== LLM Providers ===${NC}"
echo -e "${YELLOW}Configure at least ONE provider for AI features${NC}\n"

read -p "Configure OpenAI? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    OPENAI_API_KEY=$(prompt_input "OPENAI_API_KEY" "OpenAI API Key (sk-...)" "" true)
fi

read -p "Configure Anthropic Claude? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ANTHROPIC_API_KEY=$(prompt_input "ANTHROPIC_API_KEY" "Anthropic API Key (sk-ant-...)" "" true)
fi

read -p "Configure Google Gemini? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    GOOGLE_API_KEY=$(prompt_input "GOOGLE_API_KEY" "Google API Key" "" true)
fi

read -p "Configure DeepSeek? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    DEEPSEEK_API_KEY=$(prompt_input "DEEPSEEK_API_KEY" "DeepSeek API Key" "" true)
fi

read -p "Configure OpenRouter (100+ models)? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    OPENROUTER_API_KEY=$(prompt_input "OPENROUTER_API_KEY" "OpenRouter API Key (sk-or-v1-...)" "" true)
    OPENROUTER_APP_NAME=$(prompt_input "OPENROUTER_APP_NAME" "OpenRouter App Name" "nxscraper-engine")
fi

read -p "Configure Local AI (Ollama)? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    OLLAMA_BASE_URL=$(prompt_input "OLLAMA_BASE_URL" "Ollama Base URL" "http://host.docker.internal:11434")
    OLLAMA_MODEL=$(prompt_input "OLLAMA_MODEL" "Default Ollama Model" "llama3")
fi

echo ""

# Optional Features
echo -e "${BLUE}=== Optional Features ===${NC}\n"

read -p "Configure CAPTCHA Solver? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    CAPTCHA_API_KEY=$(prompt_input "CAPTCHA_API_KEY" "CAPTCHA API Key (2captcha/anticaptcha)" "" true)
fi

read -p "Configure Proxy? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    PROXY_LIST=$(prompt_input "PROXY_LIST" "Proxy List (comma-separated)" "")
    PROXY_ROTATION=$(prompt_input "PROXY_ROTATION_STRATEGY" "Proxy Rotation Strategy" "random")
fi

# Create .env file
echo -e "\n${BLUE}=== Writing Configuration ===${NC}\n"

cat > "$ENV_FILE" <<EOF
# NxScraper Engine Configuration
# Generated by setup wizard on $(date)

# Application
NODE_ENV=${NODE_ENV}
API_PORT=${API_PORT}
LOG_LEVEL=${LOG_LEVEL}
WORKER_CONCURRENCY=${WORKER_CONCURRENCY}

# Database
DRAGONFLY_URL=${DRAGONFLY_URL}
REDIS_URL=${DRAGONFLY_URL}

# Security
SESSION_ENCRYPTION_KEY=${SESSION_KEY}

EOF

# Add LLM providers
if [ -n "$OPENAI_API_KEY" ]; then
    echo "# OpenAI" >> "$ENV_FILE"
    echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "# Anthropic" >> "$ENV_FILE"
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$GOOGLE_API_KEY" ]; then
    echo "# Google Gemini" >> "$ENV_FILE"
    echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$DEEPSEEK_API_KEY" ]; then
    echo "# DeepSeek" >> "$ENV_FILE"
    echo "DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$OPENROUTER_API_KEY" ]; then
    echo "# OpenRouter" >> "$ENV_FILE"
    echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}" >> "$ENV_FILE"
    echo "OPENROUTER_APP_NAME=${OPENROUTER_APP_NAME:-nxscraper-engine}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$OLLAMA_BASE_URL" ]; then
    echo "# Ollama (Local AI)" >> "$ENV_FILE"
    echo "OLLAMA_BASE_URL=${OLLAMA_BASE_URL}" >> "$ENV_FILE"
    echo "OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$CAPTCHA_API_KEY" ]; then
    echo "# CAPTCHA Solver" >> "$ENV_FILE"
    echo "CAPTCHA_API_KEY=${CAPTCHA_API_KEY}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

if [ -n "$PROXY_LIST" ]; then
    echo "# Proxy Configuration" >> "$ENV_FILE"
    echo "PROXY_LIST=${PROXY_LIST}" >> "$ENV_FILE"
    echo "PROXY_ROTATION_STRATEGY=${PROXY_ROTATION:-random}" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

echo -e "${GREEN}✓ Configuration saved to ${ENV_FILE}${NC}\n"

# Summary
echo -e "${BLUE}=== Configuration Summary ===${NC}\n"
echo -e "Environment: ${GREEN}${NODE_ENV}${NC}"
echo -e "API Port: ${GREEN}${API_PORT}${NC}"
echo -e "Log Level: ${GREEN}${LOG_LEVEL}${NC}"
echo ""

echo -e "${BLUE}LLM Providers Configured:${NC}"
[ -n "$OPENAI_API_KEY" ] && echo -e "  ${GREEN}✓${NC} OpenAI"
[ -n "$ANTHROPIC_API_KEY" ] && echo -e "  ${GREEN}✓${NC} Anthropic"
[ -n "$GOOGLE_API_KEY" ] && echo -e "  ${GREEN}✓${NC} Google Gemini"
[ -n "$DEEPSEEK_API_KEY" ] && echo -e "  ${GREEN}✓${NC} DeepSeek"
[ -n "$OPENROUTER_API_KEY" ] && echo -e "  ${GREEN}✓${NC} OpenRouter"
[ -n "$OLLAMA_BASE_URL" ] && echo -e "  ${GREEN}✓${NC} Ollama (Local)"

if [ -z "$OPENAI_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$GOOGLE_API_KEY" ] && [ -z "$DEEPSEEK_API_KEY" ] && [ -z "$OPENROUTER_API_KEY" ]; then
    echo -e "  ${RED}⚠️  No LLM providers configured! AI features will not work.${NC}"
fi

echo ""

# Next steps
echo -e "${BLUE}=== Next Steps ===${NC}\n"
echo -e "1. Start the engine:"
echo -e "   ${YELLOW}docker compose up -d${NC}\n"
echo -e "2. Check status:"
echo -e "   ${YELLOW}curl http://localhost:${API_PORT}/health${NC}\n"
echo -e "3. View logs:"
echo -e "   ${YELLOW}docker compose logs -f core-engine${NC}\n"
echo -e "4. Access monitoring:"
echo -e "   ${YELLOW}http://localhost:3001${NC} (Grafana - admin/admin)\n"

echo -e "${GREEN}✓ Setup complete! Happy scraping! 🚀${NC}\n"
